### ISSUE TITLE
[BUG] First request to BGG API seems to fail

### ISSUE THREAD

**Issue by JDGiardino** [JDGiardino/BGG-Companion#22]
This is an actual issue that's a bug I've seen come up multiple times.  Will update with evidence the next time it happens.  But it seems like the first time calling the BGG API in awhile the return of that request is a "please wait" sort of message.  And than calling it again works.  It doesn't seem like the retry client module works for this and I think it's because a response is given from the API it's just not the real response it's like an acknowledgement of the request and a please wait pending request without actually updating it.  This causes an error in the python code for that first inital request and seems to also affect the front end.  

I will update this issue the next time it comes up.  But there will probably have to be some research here to see what exactly is happening and is the issue.

**Comment by JDGiardino** [comment]
Here's an example of the API response message
<img width="1113" alt="Screen Shot 2022-05-28 at 11 38 34 PM" src="https://user-images.githubusercontent.com/14614633/170850968-25c3787b-8a3d-4197-9f3c-eeff9265b60b.png">

**Comment by nickdibari** [comment]
I wager this is either a bot-blocking mitigation or a blip in the BGG API. You might want to add logic to your BGG API client to check if the response contains the message you have in the image above. I imagine that the response has a `200 OK` response status, but obviously is missing the data you actually need. You can consider extending the `RetryClient` class to also account for this behavior.

**Comment by JDGiardino** [comment]
Ahhhhh yes yes that totally makes sense.  I already have some exception handling for specific api responses so I'm sure it would look similar to that just in the retry client
