### ISSUE TITLE
Implementing a front end using react

### ISSUE THREAD

**Issue by halo123u** [JDGiardino/BGG-Companion#28]
It would be cool to use react for building the front end. React is heavily used in the industry and there are a lot of well tested libraries we can use to display tables or any complex features that we may need in the future. I am not entirely sure what would be the best approach for separating the front end and backend. Creating a mono repo and having a dedicated backend folder and front end folder is what I was thinking about, but open to other ideas.

**Comment by JDGiardino** [comment]
Maybe we can use the folder structure from this post https://stackoverflow.com/questions/51126472/how-to-organise-file-structure-of-backend-and-frontend-in-mern

**Comment by halo123u** [comment]
https://github.com/JDGiardino/BGG-Companion/pull/42
