### ISSUE TITLE
Enabling CORS for local development

### ISSUE THREAD

**Issue by halo123u** [JDGiardino/BGG-Companion#29]
When running a front end application in a different port than the backend, the application must allow cross origin resource sharing. This allows the front end and back end to talk to each other if they are running on diff ports.   I tried using [flask-CORS](https://flask-cors.readthedocs.io/en/latest/) but I was having issues when I tried to allow specific domains (localhost:3000). Although it's easy to allow all domains to hit any endpoint. I think BGG should restrict it to only certain domains for security and to prevent unauthorized domains from retrieving data.

**Comment by JDGiardino** [comment]
Maybe we can use the folder structure from this post https://stackoverflow.com/questions/51126472/how-to-organise-file-structure-of-backend-and-frontend-in-mern
