### ISSUE TITLE
[Bug] Cache implementation on BE isn't working as expected

### ISSUE THREAD

**Issue by halo123u** [JDGiardino/BGG-Companion#41]
I got the proxy to work in react and now i am able to hit the `/random_game` endpoint but the create react app is setup so that when you save the file, it automatically refreshes the page. For some reason I got this long message from the BE : 

`HTTPSConnectionPool(host='boardgamegeek.com', port=443): Max retries exceeded with url: /xmlapi2/collection?username=JDGiardino (Caused by ResponseError('too many 429 error responses'))`

**Comment by JDGiardino** [comment]
Ugh yeah I was experiencing something similar where I was running locally and hit random game too many times it would take awhile to load and hang there for a bit like this : 
<img width="806" alt="Screen Shot 2022-06-15 at 10 02 37 PM" src="https://user-images.githubusercontent.com/14614633/173975281-a73dfdec-57d6-4023-a62a-01977ac0d165.png">
And than would load with that same error : 
<img width="1355" alt="Screen Shot 2022-06-15 at 10 03 18 PM" src="https://user-images.githubusercontent.com/14614633/173975363-940730cf-6129-4ae5-b374-21664b64b1ed.png">

**Comment by JDGiardino** [comment]
I DO know that cacheing worked at some point.  Where I could just spam that submit button and would keep regenerating and never hang.  I only noticed this when I included the image of the game.  But this is definitely a bug to look into!

**Comment by nickdibari** [comment]
It might be that the `@cached` decorator here: https://github.com/JDGiardino/BGG-Companion/blob/main/src/bgg_companion_api.py#L23-L24 is caching the exception being thrown, when instead we only want to cache the parsed XML from these lines: https://github.com/JDGiardino/BGG-Companion/blob/main/src/bgg_companion_api.py#L25-L26

Perhaps what we could do instead is use the lower-level cache API and check the cache before making the request. We'd remove the function decorator and use the `cachetools.TTLCache` cache directly, like so:

```python
cache = cachetools.TTLCache(maxsize=500, ttl=300)

def get_collection(self, user: str) -> dict:
    if not cache.get(user):
        # make request to get XML and parse into dictr
        cache[user] = xml_parse
```

**Comment by JDGiardino** [comment]
https://realpython.com/lru-cache-python/

**Comment by JDGiardino** [comment]
https://flask-caching.readthedocs.io/en/latest/#explicitly-caching-data
