### ISSUE TITLE
Auto-complete user field with the last user a client provided

### ISSUE THREAD

**Issue by JDGiardino** [JDGiardino/BGG-Companion#46]
**User Story** : 
As a User, it would be a nice experience if the field for providing a BoardGameGeek user was automatically populated with the last user I provided. 

**Technical Details** :

- This will involve a basic implementation of cookies in flask
- A cookie will have to be set at the point in time a user is set as a argument
- A cookie will have to be requested at the point the html is rendered

**Documentation** :

- https://flask.palletsprojects.com/en/2.1.x/quickstart/#cookies
- https://flask.palletsprojects.com/en/2.1.x/api/?highlight=cookies#flask.Request.cookies
- https://flask.palletsprojects.com/en/2.1.x/api/?highlight=cookies#flask.Response.set_cookie

**Acceptance Criteria** : 

1. When I enter a user for a random game, when I reload the page that same user is pre-populated in the field
2. End-user has the option to either have their username saved or not

**Comment by nickdibari** [comment]
nit: you might also want to give people the option to save their name or not; i can imagine there's some privacy preferences folks might have with regards to saving their name. you can add a checkbox or something on the homepage that says "Save my username" or something to give people the option to save their username as a cookie, and have logic in the view to either set the cookie or not depending on if the user clicked the checkbox.
